# fly.toml app configuration file generated for facturaelectronica on 2023-08-14T08:04:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "facturaelectronica"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
